services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/13/main/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/13/main/postgresql.conf
    networks:
      network:
        ipv4_address: 172.99.0.2

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "8200:8978"
    volumes:
      - .workspace:/opt/cloudbeaver/workspace
    networks:
      network:
        ipv4_address: 172.99.0.3

  metabase:
    image: metabase/metabase:latest
    restart: always
    depends_on:
      - cloudbeaver
    ports:
      - "3000:3000"
    networks:
      network:
        ipv4_address: 172.99.0.4

volumes:
  pg_data:

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
          gateway: 172.99.0.1
